---
- name: Install grafana-kiosk dependencies
  package:
    name: "{{ grafana_kiosk_dependencies }}"
    state: present
    
- name: Creates directory for auto-login config
  ansible.builtin.file:
    path: /etc/systemd/system/getty@tty1.service.d/
    state: directory

- name: "Configure auto-login for user {{ grafana_kiosk_user }} on tty1"
  template:
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    src: getty@tty1.service.j2
    mode: '664'

- name: "Enable auto-login for user {{ grafana_kiosk_user }} on tty1"
  systemd:
    daemon_reload: true
    name: getty@tty1
    enabled: true

- name: Create .profile to start graphical interface
  file:
    path: /home/{{ grafana_kiosk_user }}/.profile
    state: file

- name: Test if .profile needs updating
  shell: grep -c "{{ grafana_kiosk_profile_graphical_startup }}" /home/{{ grafana_kiosk_user }}/.profile || true
  register: startx_grep

- name: Configure .profile to start graphical interface on login
  lineinfile:
    dest: /home/{{ grafana_kiosk_user }}/.profile
    line: "{{ grafana_kiosk_profile_graphical_startup }}"
  when: startx_grep.stdout == "0"

- name: Create openbox autostart directory
  file:
    path: /home/{{ grafana_kiosk_user }}/.config/openbox/
    state: directory

- name: Create openbox autostart configuration
  template:
    dest: /home/{{ grafana_kiosk_user }}/.config/openbox/autostart
    src: openbox-autostart.j2

- name: Create grafana-kiosk directory
  file:
    path: /home/{{ grafana_kiosk_user }}/grafana-kiosk/
    owner: "{{ grafana_kiosk_user }}"
    state: directory

- name: Download grafana-kiosk
  get_url:
    dest: /home/{{ grafana_kiosk_user }}/grafana-kiosk/
    url: https://github.com/grafana/grafana-kiosk/releases/download/v1.0.9/grafana-kiosk.linux.armv7
    owner: "{{ grafana_kiosk_user }}"
    mode: '744'

- name: Copy grafana-kiosk configuration file
  copy:
    dest: /home/{{ grafana_kiosk_user }}/grafana-kiosk/grafana-kiosk-config.yaml
    owner: "{{ grafana_kiosk_user }}"
    src: "{{ grafana_kiosk_config_yaml }}"
